import argparse

parser = argparse.ArgumentParser(description="Traning options",
                                 formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument("dataset", help="Dataset location for .npz files")
parser.add_argument("-n", "--n-strokes", action="store", help="the maximum number of sketch strokes", default=128)
parser.add_argument("-t", "--train-samples", action="store", help="the number of samples for train set per class", default=5000)
parser.add_argument("-v", "--valid-samples", action="store", help="the number of samples for valid set per class", default=1000)
parser.add_argument("-c", "--classes", action="store", help="the number of output classes", default=345)
parser.add_argument("-e", "--epochs", action="store", default=50)
parser.add_argument("-b", "--batch-size", action="store", default=64)
parser.add_argument("-l", "--lr", action="store", help="learning rate", default=1e-3)
parser.add_argument("--model-state", action="store")
parser.add_argument("--logs", action="store", default="log.json")
parser.add_argument("--save-figures", action="store", help="directory name", default="figures")
parser.add_argument("--batch-norm", action="store_true", help="use batch normalization")
parser.add_argument("--cuda", action="store", help="cuda number to use", default=0)
args = parser.parse_args()
config = vars(args)
print(config)
